### ISSUE TITLE
Add this cool feature to github.io

### ISSUE THREAD

**Issue by gabyx** [Mottie/GitHub-userscripts#1]
Could we have the table of content buttoin also on ``github.io`` that would be awesome

**Comment by Mottie** [comment]
Hmm, do you mean the gh-pages? Not every page is the same, and I'm not sure if the rendered markdown classes are the same. Do you have an example page?

**Comment by gabyx** [comment]
The following page here:

http://gabyx.github.io/GRSFramework/

this index.html directly loads the Home.md from the wiki and then renders the markdown :-)

It would be the most handiest, if I could send the inner html of my 
 
``<div id="content">...</div>``

to your java script function which (wenn the TOC button is pressed) 
reads the innerHTML of ``<div id="content">...</div>`` , parses the stuff into a TOC and renders the TOC.

So would it be possible to include all the java script directly on my index.html page
and then call some function (which one? :-)) which displayes the TOC?

Would be awesome to have that. But I am not really JavaScript geek.

Maybee one could add a simple wiki entry to show which steps need to be taken to make that happen.

**Comment by Mottie** [comment]
Honestly, because you're using gh-pages, I think you might be happier with a side menu. Something like:

* http://takien.github.io/jPushMenu/
* https://www.berriart.com/sidr/
* http://callmenick.com/post/slide-and-push-menus-with-css3-transitions
* http://getbootstrap.com/javascript/#scrollspy (a bit more complicated to set up)

I could get you started... I'll work on something when I get some free time.

**Comment by Mottie** [comment]
Done: https://github.com/gabyx/GRSFramework/pull/1

**Comment by gabyx** [comment]
Thanks for your input :-)
Due to that, I am no able to fully parse the rendered markdown into a sidebar TOC :-) pretty awesome, I added some +/- expand buttons on top =), thanks for your help .-)

http://gabyx.github.io/GRSFramework/

**Comment by Mottie** [comment]
Nice work! :grinning:
