### ISSUE TITLE
[Toggle Expanders] Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by aspiers** [Mottie/GitHub-userscripts#101]
When following the link from https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-toggle-expanders to https://github.com/torvalds/linux/commits/master, if I Control+Shift+click on a commit, nothing expands, and in my Javascript console I see:

```
userscript.html?id=0fae92d5-5b1e-4dfe-b375-9b8c648189cd:30 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at toggle (userscript.html?id=0fae92d5-5b1e-4dfe-b375-9b8c648189cd:30)
    at Window.eval (userscript.html?id=0fae92d5-5b1e-4dfe-b375-9b8c648189cd:52)
    at <anonymous>:2:494
    at c.<computed> (eval at exec_fn (master:1), <anonymous>:55:182)
```

**Comment by Mottie** [comment]
Hi @aspiers!

I was just working on this fix.

I was thinking about changing it so that <kbd>Shift</kbd>+Click only toggle the expanders of the current date. Then <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+Click would toggle all expanders on the page. This is different that the previous behavior where <kbd>Shift</kbd>+Click  would toggle all the expanders and including the <kbd>Ctrl</kbd> did nothing different (except for the outdated blocks). What do you think of this change?

**Comment by aspiers** [comment]
Thanks @Mottie!  Yes, this sounds exactly right to me.

**Comment by Mottie** [comment]
This has been fixed in the latest version!

**Comment by aspiers** [comment]
Works perfectly, thanks again :-)
