### ISSUE TITLE
[GitHub-sort-content] Sort repo broken

### ISSUE THREAD

**Issue by gingerbeardman** [Mottie/GitHub-userscripts#104]
Sort repo seems to be broken?

See https://github.com/isaacs/github/issues/895#issuecomment-552079088

**Comment by Mottie** [comment]
Hi @gingerbeardman!

Hmm, yeah I think you're right. I won't be able to troubleshoot or work on this right now, but I'll take a look soon. Thanks for letting me know!

**Comment by redtide** [comment]
After looking at other issue comments I tried to replace Greasemonkey with Tampermonkey, installing the script this time from the GH repo but didn't help.

**Comment by Mottie** [comment]
I recently had to rewrite that userscript because GitHub had changed so many class names. I used the same list of targeted pages, so I'm not sure if I missed that one. I'm in the process of re-installing Windows, so my dev environment isn't set up... and we have plans today. So I probably won't get to look at this until later tonight.

**Comment by Mottie** [comment]
Yep, GitHub changed the attributes I was targeting. All fixed!

**Comment by gingerbeardman** [comment]
Thank you!
