### ISSUE TITLE
monospace font toggle breaks PR UI

### ISSUE THREAD

**Issue by aspiers** [Mottie/GitHub-userscripts#11]
If I view a PR's main page with the monospace font toggle userscript enabled, the cog icons on the right hand side for setting projects, labels, milestones, assignees all vanish.  This makes the userscript effectively unusable.

**Comment by Mottie** [comment]
Hi @aspiers!

I can't seem to duplicate this issue. I did have to update the userscript to fix the button title & color (see https://github.com/StylishThemes/GitHub-Dark-Script/commit/474e1eb905495b2160c43203dbed81631385bd05).

![monospace-toggle](https://cloud.githubusercontent.com/assets/136959/18964823/22783022-8640-11e6-8d8e-53d5e587bbe8.gif)

**Comment by Mottie** [comment]
Please note that there are two separate monospace font code sources. One is the `github-script-monospace-toggle.user.js` script, shown above. The second is built into the GitHub Dark script (`github-dark-script.user.js`).

**Comment by aspiers** [comment]
Yeah, I'm using the standalone userscript not the Dark one.  When I have it installed, those cogs on the right-hand side simply vanish.  When I disable the userscript and reload the page, they come back.  I'm semi-competent with Javascript, however my brain's not functioning 100% right now, so when I stare at the source I can't immediately see what the various functions do and how they combine together.  Maybe if you gave me a few tips and/or a quick overview I could figure out how to debug it myself.

**Comment by Mottie** [comment]
Inside the `addBindings` function at line 65:

* A click on the body checks if the `event.target` has a "ghd-monospace" class name - it's the toggle button added inside of each comment block.
* If clicked, it finds the closest comment wrapper (`preview-comment-form`) which is applied to both new comments and edited comments.
* It then targets the `comment-form-textarea` and toggles the `ghd-monospace-font` class name. CSS definitions for that class name are added by the `GM_addStyle` function.
* The target icon then has a "text-blue" class (defined by GitHub's stylesheet) to indicate of the toggle is active, or not.

I probably should change the `closest` function to the following, since I've found that you don't really need to use a polyfill for `matches`:

```js
function closest(el, selector) {
  while (el && el.nodeName !== 'BODY' && !el.matches(selector)) {
    el = el.parentNode;
  }
  return el && el.matches(selector) ? el : [];
}
```

**Comment by Mottie** [comment]
I just updated this script again to use ES6, and the `closest` function I shared above in https://github.com/StylishThemes/GitHub-Dark-Script/commit/b1220bb2b28169e5356f3741bf32f0c804fb54aa.

Please try it out and see if the same problem persists.

**Comment by aspiers** [comment]
Wow - it's fixed now! Thanks :-D
