### ISSUE TITLE
Sort file listing?

### ISSUE THREAD

**Issue by gingerbeardman** [Mottie/GitHub-userscripts#24]
Would expect it in GitHub Sort Content.

But have also checked GitHub Files Filter, no joy.

Currently I see:

![screen shot 2017-07-03 at 13 27 29](https://user-images.githubusercontent.com/49612/27793138-ad8ab3a4-5ff4-11e7-8e24-f392faba0107.png)

**Comment by Mottie** [comment]
Hi @gingerbeardman!

I didn't include the sorting in the `GitHub sort content` userscript because it adds the sort arrows as a background image and the file view doesn't have a header that can be targeted. I found [this userscript](https://github.com/trespassersW/UserScripts/blob/master/show/GHSFl.md) a while back that adds clickable arrows to allow sorting, so I didn't think it would be necessary for me to repeat the work. It's not really "pretty" though 😉.

I guess it would be a good idea to include it in the sort content script... I'll put it on my to-do list.

**Comment by gingerbeardman** [comment]
@Mottie thanks for the link, sadly that still keeps folders and files separate 😭 

Although easy enough to change that script once it's installed. Cheers!

Would still use your solution if you ever do one. 👍

**Comment by Mottie** [comment]
It was easier to add then I thought 😸

**Comment by gingerbeardman** [comment]
@Mottie beauty! many thanks

**Comment by Mottie** [comment]
Hehe, I think it actually looks kinda ugly, but what can ya do?

**Comment by gingerbeardman** [comment]
you adding it was beautiful, it looks... passable 😄

**Comment by gingerbeardman** [comment]
strangely, is only appears if i get to a page and reload it?

if i get to a page through browsing it doesn't appear?

https://transfer.sh/KKCTo/quirk.mov

**Comment by Mottie** [comment]
Yeah, it's very fussy... the files within the table are added after the page loads, so sometimes it acts that way. I have the same issue with the file filter userscript. If you look at the bottom of the code, you'll see this block:

```js
		// init after a short delay to allow rendering of file list
		setTimeout(() => {
			addRepoFileThead();
		}, 200);
```

Try increasing the `200` ms a little bit and see if that helps. I'll keep searching for a better solution.
