### ISSUE TITLE
(GitHub code show whitespace) shows space character on empty lines?

### ISSUE THREAD

**Issue by animatedantmo** [Mottie/GitHub-userscripts#65]
I am using version Chrome Version 71.0.3578.98, 1.2.4 of the GitHub code show whitespace script and the split view for diffs. I am not sure if this is how things always were displayed but I noticed that each line is being prefixed with a white space character. It even seems to throw off the display of lines that only contain line breaks. 

This is the scss file as displayed with the script

![screen shot 2018-12-20 at 8 22 54 am](https://user-images.githubusercontent.com/11149609/50287353-7a66a780-0430-11e9-82b9-39623623c220.png)

This is that same scss file as displayed in my editor with whitespace displayed

![screen shot 2018-12-20 at 8 26 32 am](https://user-images.githubusercontent.com/11149609/50287506-f95be000-0430-11e9-9272-c93ff720657c.png)

Notice line 8 in the editor vs how its displayed in the diff, specifically the way it seems to wrap.
Is there something I should be doing differently?

**Comment by Mottie** [comment]
Hi @animatedantmo!

It looks like a code wrap style or script is being applied. When the code wraps, the new line will start at the beginning of the line. If not, then maybe it is this userscript's fault because it's adding content to make the whitespace visible.

When I have the [code wrap toggle](https://github.com/StylishThemes/GitHub-Dark-Script#toggles) script running, I'm seeing the same thing; but my question is what are you expecting to happen when the code wraps?

**Comment by Mottie** [comment]
Hmm, I'm not sure you're seeing something different from me.

Previously... on the diff views, GitHub would add an extra space (or two?) to every line to allow space for the `+` and `-` in the diff. Now, they add the indicator to a pseudo element so people can copy/paste the code without the indicators.

I'm no longer seeing a leading space, or a space next to the `+` like in your screenshot.

![](https://user-images.githubusercontent.com/136959/50324826-d2d88c00-04a6-11e9-9ea5-453c3d8eeef5.gif)

GitHub also sets their tab indent to be 8 spaces. You'll see that change to 2 spaces because of my GitHub Dark setting.

**Comment by animatedantmo** [comment]
Ive added added a different white space rendering script to debug a bit and that leading whitespace is still there. But without the odd wrapping if that helps

https://github.com/glebm/render-whitespace-on-github

<img width="334" alt="screen shot 2018-12-20 at 11 45 59 pm" src="https://user-images.githubusercontent.com/11149609/50325231-a413e300-04b1-11e9-9609-666306e99e94.png">

**Comment by Mottie** [comment]
Is this still an issue?

**Comment by animatedantmo** [comment]
Yes, looks like this is still happening with version 1.2.6

This is what the "GitHub Code Show Whitespace" script displays

<img width="310" alt="odd" src="https://user-images.githubusercontent.com/11149609/52917859-0759a000-32be-11e9-8a0c-4a5a3696c32e.png">

This is what the "Render Whitespace on GitHub" script displays

<img width="293" alt="ok" src="https://user-images.githubusercontent.com/11149609/52917862-0c1e5400-32be-11e9-8c51-e011a0c87467.png">

Notice the odd display/line breaking happening on 103 and 107. The second display is what I would expect.

**Comment by Mottie** [comment]
Please share a link to the page where you see this issue. For me, the carriage returns in the JS files in this repo are not adding an extra CR that I see in the screenshots.

**Comment by animatedantmo** [comment]
The repo is private but I went ahead and setup a shell angular project with a PR that exhibits the issue. Please take a look at

https://github.com/animatedantmo/test/pull/1/files

**Comment by Mottie** [comment]
Ok, so it looks like GitHub is adding an extra `<br>` inside the code block. I just hid it and it looks good now. Hopefully that doesn't mess up anything else.
